### ISSUE TITLE
Strange error with QuickCheck property

### ISSUE THREAD

**Issue by marcosh** [martijnbastiaan/doctest-parallel#50] opened 2022-08-24 08:18 UTC
If I try to copy the example property from the documentation

```haskell
-- |
-- prop> \xs -> sort xs == (sort . sort) (xs :: [Int])
```

I get the following error message when I run `stack test`

```
Progress 1/2: haskell-training/home/marcosh/projects/tweag/haskell-training/src/Forms.hs:52: failure in expression `\xs -> sort xs == (sort . sort) (xs :: [Int])'

<interactive>:44:2: error:
    • No instance for (Show ([Int] -> [Int]))
        arising from a use of ‘Test.QuickCheck.Test.quickCheck’
        (maybe you haven't applied a function to enough arguments?)
    • In the expression: Test.QuickCheck.Test.quickCheck doctest_prop
      In an equation for ‘it’:
          it = (Test.QuickCheck.Test.quickCheck doctest_prop)
```

**Comment by martijnbastiaan** [comment] 2022-08-29 15:42
It looks like this error is caused by `sort` being out of scope. Note entirely sure why this error message pops up, but the following setup statement works:

```haskell
{- $setup
>>> import Data.List (sort)
-}
```

**Comment by marcosh** [comment] 2022-08-31 06:49
oh, I see! Thanks!

Probably `sort`, if not imported, is interpreted as a value to be generated.

It's probably enough to clarify this in the documentation

**Comment by martijnbastiaan** [comment] 2022-08-31 06:54
Makes sense. I'll change the example to something in scope by default too, like `abs`.

**Closed** 2022-12-23 12:28 UTC
Labels: documentation, enhancement
